on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1: Build - tests
  build:
    uses: MigracaoDotNetForms/ci-cd-pipelines/.github/workflows/reusable-build.yml@main
    with:
      solution_name: 'Projeto_Windows.sln'
      build_configuration: 'Release'
      test_path: './Projeto_WindowsTeste/Projeto_WindowsTeste.csproj'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      

  #3: deploy
  deploy:
    needs: build
    uses: MigracaoDotNetForms/ci-cd-pipelines/.github/workflows/release-deploy.yml@main
    with:
      solution_name: 'Projeto_Windows.sln'
      test_path: './Projeto_WindowsTeste/Projeto_WindowsTeste.csproj'
      exe_path: './Projeto_Windows/bin/Release/Projeto_Windows.exe'