on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1: Build - tests
  build:
    #uses: MigracaoDotNetForms/ci-cd-pipelines/.github/workflows/reusable-build.yml@main
    uses: sarafogo/pipeline_templates/.github/workflows/build.yml@main
    secrets: inherit

  #3: deploy
  deploy:
    needs: build
    uses: MigracaoDotNetForms/ci-cd-pipelines/.github/workflows/release-deploy.yml@main