name: Build 
on:
  push:
    branches:
      - main 
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Setup NuGet
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Oficial SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v5.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
         -Dsonar.organization='migracaodotnetforms'
         -Dsonar.projectKey=${{ github.repository }}
         -Dsonar.verbose=true
         -Dsonar.exclusions=**/bin/**/*,**/obj/**/*,**/packages/**/*,**/test/**/*

    # Build the project
    - name: Build solution
      run: msbuild Projeto_Windows.sln /p:Configuration=Release

    # Run Save Artifacts
    - name: Save Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Projeto_WindowsTeste
        path: Projeto_Windows\Projeto_WindowsTeste\bin\Release

    # Run tests
    - name: Run tests
      run: |
        $dlls = Get-ChildItem -Path "Projeto_WindowsTeste\bin\Debug" -Filter "*.Tests.dll"
        foreach ($dll in $dlls) {
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" `
          $dll.FullName `
          /Logger:trx
        }
      shell: pwsh


